--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/PocketMine-Community/WorldManager
build-by-default: true
branches:
- main
projects:
  WorldManager:
    path: ""
    icon: "icon.png"
...
