name: WorldManager
main: PocketMineCommunity\WorldManager
version: 1.0.0
api: 5.0.0
author: PocketMine Community

permissions:
  worldmanager.command:
    default: op
  worldmanager.subcommand.help:
    description: Allows using the help subcommand
    default: true
  worldmanager.subcommand.region:
    description: Allows using region management commands
    default: op
  worldmanager.subcommand.delete:
    description: Allows deleting worlds
    default: op
  worldmanager.subcommand.duplicate:
    description: Allows duplicating worlds
    default: op
  worldmanager.subcommand.list:
    description: Allows listing worlds
    default: true
  worldmanager.subcommand.tp:
    description: Allows teleporting to worlds
    default: op
  worldmanager.subcommand.create:
    description: Allows creating worlds
    default: op
  worldmanager.subcommand.load:
    description: Allows loading worlds
    default: op
  worldmanager.subcommand.unload:
    description: Allows unloading worlds
    default: op
  worldmanager.subcommand.rename:
    description: Allows renaming worlds
    default: op